name: Validate

on:
  release:
  workflow_dispatch:

jobs:
  validate-hacs:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
